version: "2.0"

services:

  # Solr instance for running tests against
  solr:
    image: ukwa/webarchive-discovery-solr
    ports:
      - 8983:8983

  # WarcLight
  warclight:
    build: .
    environment:
     - "SOLR_URL=http://solr:8983/solr/discovery"
    ports:
     - 3000:3000


